---
- name: data collection from Meraki API
  hosts:
  - meraki
  strategy: free
  gather_facts: no
  tasks:
  - name: collect all available data from Meraki API nodes
    action: ndmtk
        output="/opt/data/devnet-meraki/meraki-%Y%m%d%H%M%S"
        no_host_key_check=yes
        on_error=continue
        safe="./ansible.vault.yml"
        lockpick="./ansible.vault.key"
