---
- name: OSPF configuration
  hosts:
  - sandbox
  strategy: free
  gather_facts: no
  tasks:
  - name: configure ospf on DevNet Sandbox nodes
    action: ndmtk
        disable_defaults=yes
        cliset_spec=files/ndmtk/spec/configure_ospf_{{ os }}.yml
        output="/opt/data/devnet-sandbox/nxapi-conf-ospf-%Y%m%d%H%M%S"
        no_host_key_check=yes
        on_error=continue
        safe="./ansible.vault.yml"
        lockpick="./ansible.vault.key"
